"""empty message

Revision ID: e2361e31822b
Revises: b6e6232433c6
Create Date: 2024-08-16 20:34:16.594688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2361e31822b'
down_revision = 'b6e6232433c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
